apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name}}
  namespace: {{ .Values.namespaces }}
  labels:
    app: {{ .Values.app.name}}
spec:
  ports:
  - port: 80
    protocol: TCP
    name: flask
  selector:
    app: {{ .Values.app.name}}
    tier: frontend
  type: NodePort